---
title: "covid_diabetes_microvascular"
author: "Zoe Zhu"
date: "8/25/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE, warning = FALSE)
```

## Diabetes patients with COVID
### load libraries
```{r libraries}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(gmodels)# used for logistic regression 
```


##Read data
```{r read data, echo=FALSE}
data= read.csv('try.csv') # data from python cleaning
#data
```

##calcualte death rate and CI by group
```{r calculate rate and CI by group}
df1 = data %>% filter(category == 'any')
table(df1$status)
prop.test(342,n = 1364, conf.level=0.95, correct = FALSE)
mytable <- table(data$status,data$category)
summary(mytable)
```

```{r build logisitic regression adjusted by age and gender}
logmodel1 <- glm(AdmissionMortality~ relevel(factor(new),ref = 'nocomplication') + c(PatientAge)+c(Gender), data = data,family =  binomial) # no complication as reference level 
```
```{r odds ratio and confidence interval}
or <- exp(logmodel1$coefficients)# odds ratio by exponent the coefficients
summary(logmodel1)
round(cbind(or, exp(confint(logmodel1))),2)# looked at adjusted odds ratio
confint(oddsratio(death, log=FALSE), level = 0.95)# look at confidence interval
```

